using UnityEngine;
using UnityEngine.UI;

public class TimerScript : MonoBehaviour
{
    public float Timer;
    public bool TimerOn = false;

    public Text TimerTxt;

    void Start()
    {
        TimerOn = true;
    }

    void Update()
    {
        if (TimerOn)
        {
            if (Timer >= 0)
            {
                Timer += Time.deltaTime;
                updateTimer(Timer);
            }
            else
            {
                
                Timer = 0;
                TimerOn = false;
            }
        }
    }

    void updateTimer(float currentTime)
    {
        currentTime += 1;

        float minutes = Mathf.FloorToInt(currentTime / 60);
        float seconds = Mathf.FloorToInt(currentTime % 60);

        TimerTxt.text = string.Format("{0:00}:{1:00}", minutes, seconds);
    }

}